### ISSUE TITLE
Error on yarn run ios

### ISSUE THREAD

**Issue by rjpalermo1** [davidrichard23/react-native-redux-parse#1]
Hello David,

So.....YARN and NPM install (tried new clones with each)

Added `import { AsyncStorage } from 'react-native/Libraries/react-native/react-native-implementation.js` to `StorageController.react-native.js` (your instructions say replace but there is no other import to replace other than `import ParsePromise from './ParsePromise';`)

On `yarn run ios` and `npm run ios` both throw the same error `ENOENT: no such file or directory, uv_chdir`

```node
ENOENT: no such file or directory, uv_chdir

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Purple@0.1.0 ios: `react-native run-ios`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Purple@0.1.0 ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I am using node -v 8.6.0 and most recent create-react-app v1.4.1

Any ideas...?

**Comment by davidrichard23** [comment]
I think I figured out what's going on. Should have it fixed soon.

**Comment by davidrichard23** [comment]
Ok it should be fixed. Turns out I didn't commit the iOS and Android folders. Also if you want to use Facebook login, you have to follow the instructions [here](https://github.com/facebook/react-native-fbsdk)

Adding this to the readme now

**Comment by rjpalermo1** [comment]
Ok cool, will try it out in a few and report back.

One thing confusing is in your instructions you have "What you need to is
change the import line in
node_modules/parse/lib/react-native/StorageController.react-native.jsto import
{ AsyncStorage } from
'react-native/Libraries/react-native/react-native-implementation.js' until
the Parse JS SDK is updated."

What exactly needs to be changed?  The only import line in that file is
import ParsePromise from './ParsePromise';

**Comment by davidrichard23** [comment]
Seeing new problems building for iOS, looking into it.

**Comment by rjpalermo1** [comment]
Ouch...

after yarn to install dependencies ~ yarn run ios returns:

*****

Loading dependency graph, done.

Bundling `index.ios.js`  [development, non-minified, hmr disabled]  0.0%
(0/1), failed.

error: bundling failed: "Cannot find entry file index.ios.js in any of the
roots: [\"/Users/Me/platform/projects/sandbox/react-native-parse\"]"


*****

**Comment by davidrichard23** [comment]
Ok everything seems to be running smoothly. Let me know if you run into any issues. I updated the README for your previous question
