### ISSUE TITLE
undefined is not a function (evaluating 'addListener')

### ISSUE THREAD

**Issue by travisjbeck** [davidrichard23/react-native-redux-parse#2]
I just recently tried to run your project and ran into this error.

![image](https://user-images.githubusercontent.com/254547/41803100-57d4ea1a-764b-11e8-8ab1-7bc8b9f6361d.png)

**Comment by davidrichard23** [comment]
Sorry for the delayed response. I actually just completely refactored the project. The code and project structure is much cleaner and easier to understand. I also updated the README with better instructions
